# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snowflake_id_development
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.labels.database == true
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  base: &base
    build: .
    image: kokorolee/snowflake_id
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      WORKER_ID: "{{.Task.Slot}}"
      DATACENTER_NAME: "{{ .Node.Hostname }}"
    deploy:
      replicas: 0
  web:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    # command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"

    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 20M
volumes:
  postgres_data:

networks:
  monitoring:
