apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/snowflake-id-default: "true"
        io.kompose.service: logstash
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: logging_l
                    operator: In
                    values:
                      - "true"
      containers:
        - image: docker.elastic.co/logstash/logstash:7.12.1
          name: logstash
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
            - containerPort: 12201
              hostIP: 127.0.0.1
              hostPort: 12201
              protocol: UDP
          resources:
            limits:
              cpu: 500m
              memory: "268435456"
            requests:
              cpu: 100m
              memory: "20971520"
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-cm0
              subPath: logstash.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: logstash.conf
                path: logstash.conf
            name: logstash-cm0
          name: logstash-cm0
