# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 5432
        hostPort: 5432
        protocol: TCP
    labels:
      database: "true"
  - role: worker
    labels:
      web: "true"
  - role: worker
    labels:
      web: "true"
