apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.network/snowflake-id-default: "true"
    io.kompose.service: db
  name: db
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: database
  #               operator: In
  #               values:
  #                 - "true"
  containers:
    - env:
        - name: POSTGRES_DB
          value: snowflake_id_development
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
      image: postgres:14
      name: db
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.1"
          memory: "20Mi"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database
  restartPolicy: OnFailure
  volumes:
    - name: database
      persistentVolumeClaim:
        claimName: database
