apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.network/snowflake-id-default: "true"
    io.kompose.service: web
  name: web
spec:
  containers:
    - args:
        - bash
        - -c
        - rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'
      env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATACENTER_NAME
          value: '{{ .Node.Hostname }}'
        - name: RAILS_ENV
          value: development
        - name: WORKER_ID
          value: '{{.Task.Slot}}'
      image: kokorolee/snowflake_id
      name: web
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
      resources:
        limits:
          cpu: "0.25"
          memory: "128Mi"
        requests:
          cpu: "0.1"
          memory: "20Mi"
  restartPolicy: OnFailure
