apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: kokorolee/snowflake_id
        env:
        - name: RAILS_ENV
          value: developmet
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        ports:
        - containerPort: 3000
